import React,{useState}from"react";import{createRoot}from"react-dom/client";import{ArrowRight,CalendarDays,Check,Clock3,Instagram,MapPin,Menu,Scissors,ShoppingBag,Star,X}from"lucide-react";import"./styles.css";
const services=[["Signature Cut","$45","Precision cut, consultation, hot towel finish"],["Skin Fade","$55","Detailed fade, line-up and styling"],["Beard Ritual","$35","Shape, hot towel treatment and finish"],["Cut + Beard","$70","Complete grooming session for the full look"]];
const products=[["VELORA Matte Clay","$24","Strong hold • Natural finish"],["Daily Beard Oil","$22","Cedar • Bergamot • Sandalwood"],["Premium Grooming Kit","$48","Comb • brush • oil • travel case"]];
function App(){const[m,setM]=useState(false),[booked,setBooked]=useState(false);return <div>
<header className="nav"><a className="logo" href="#home">VELORA<span>.</span></a><button className="mobile" onClick={()=>setM(!m)}>{m?<X/>:<Menu/>}</button><nav className={m?"open":""}>{["Services","Work","Shop","About","Contact"].map(x=><a key={x} href={"#"+x.toLowerCase()} onClick={()=>setM(false)}>{x}</a>)}<a className="navCta" href="#book">Book a chair <ArrowRight size={16}/></a></nav></header>
<main id="home">
<section className="hero"><div><p className="eyebrow"><span/> ATLANTA • EST. 2014</p><h1>Cut sharp.<br/><em>Feel sharper.</em></h1><p className="lead">A modern grooming experience built around precision, personality, and the details that make your style yours.</p><div className="actions"><a className="primary" href="#book">Book an appointment <ArrowRight size={18}/></a><a className="ghost" href="#work">Explore our work</a></div><div className="proof"><span><Star size={15} fill="currentColor"/> 4.9/5</span><b>•</b><span>1,200+ clients</span><b>•</b><span>Same-day slots</span></div></div><div className="heroVisual"><div className="portrait"><div className="portraitText">PRECISION<br/><small>GROOMING</small></div></div><div className="floating"><Scissors size={17}/><div><strong>YOUR LOOK,</strong><small>OUR CRAFT</small></div></div></div></section>
<div className="marquee"><span>PRECISION CUTS</span><i>✦</i><span>BEARD RITUALS</span><i>✦</i><span>MODERN GROOMING</span><i>✦</i><span>PRECISION CUTS</span></div>
<section id="services" className="section"><div className="head"><div><p className="eyebrow">THE MENU</p><h2>Services made<br/><em>for your signature.</em></h2></div><p>From a clean daily cut to a full grooming reset, every appointment is built around detail.</p></div><div className="serviceGrid">{services.map(([n,p,d],i)=><article className="service" key={n}><span>0{i+1}</span><h3>{n}</h3><p>{d}</p><strong>{p}</strong><a href="#book">Book <ArrowRight size={16}/></a></article>)}</div></section>
<section id="work" className="section dark"><div className="head"><div><p className="eyebrow">THE WORK</p><h2>Built around<br/><em>the details.</em></h2></div><p>Use this gallery for real client transformations, fades, beard work and your strongest cuts.</p></div><div className="gallery"><div className="tile t1">FADE <span>01</span></div><div className="tile t2">TEXTURE <span>02</span></div><div className="tile t3">BEARD <span>03</span></div><div className="tile t4">CLASSIC <span>04</span></div></div></section>
<section id="shop" className="section shop"><div className="head"><div><p className="eyebrow">THE SHOP</p><h2>Take the<br/><em>experience home.</em></h2></div><ShoppingBag/></div><div className="productGrid">{products.map(([n,p,d])=><article className="product" key={n}><div className="productVisual"><ShoppingBag size={28}/></div><div className="productInfo"><h3>{n}</h3><p>{d}</p><strong>{p}</strong></div></article>)}</div></section>
<section id="about" className="section about"><div><p className="eyebrow">WHY VELORA</p><h2>More than a cut.<br/><em>A ritual.</em></h2><p className="body">Every detail is designed to make the chair feel like your space. Relaxed service, serious craft, and a look that works when you leave the shop.</p><div className="checks"><span><Check/> Personal consultation</span><span><Check/> Premium products</span><span><Check/> Experienced barbers</span></div></div><div className="stats"><div><strong>10+</strong><span>Years of craft</span></div><div><strong>8</strong><span>Barbers</span></div><div><strong>1.2k+</strong><span>Happy clients</span></div><div><strong>14</strong><span>Services</span></div></div></section>
<section id="book" className="booking"><div><p className="eyebrow">RESERVE YOUR CHAIR</p><h2>Ready for your<br/><em>next look?</em></h2><p>Choose a time that works for you. We'll take care of the rest.</p></div><button className="primary" onClick={()=>setBooked(true)}><CalendarDays/> Book an appointment <ArrowRight/></button>{booked&&<div className="notice">Demo booking received — connect this to the client's real booking system.</div>}</section>
<section id="contact" className="section contact"><div><p className="eyebrow">FIND US</p><h2>Come through.</h2><p><MapPin size={17}/> 123 Peachtree Street, Atlanta, GA</p><p><Clock3 size={17}/> Tue–Sat · 9:00 AM–8:00 PM</p></div><div className="contactRight"><p>For appointments, collaborations, product orders or questions.</p><a href="mailto:hello@velora.demo">hello@velora.demo</a><a href="tel:+14045550147">+1 (404) 555-0147</a></div></section></main>
<footer><div className="logo">VELORA<span>.</span></div><p>Premium barbering & grooming — demo concept.</p><div><Instagram size={18}/> © 2026 VELORA</div></footer></div>}createRoot(document.getElementById("root")).render(<App/>);